### PR TITLE
Assign keywork for RD_SMSPEC_NETWORK_VAR

### LINKED ISSUE #943: EclSum doesn't read network vectors
Network vectors from `intersect` are not imported.

This has been resolved in ResInsight in their local copy

https://github.com/OPM/ResInsight/pull/8990

### PR DESCRIPTION
**Pull request by andreas-el**
**Issue**
Resolves #943 

Picks changes from commit https://github.com/OPM/ResInsight/pull/8990/commits/70f31aa4e9109ad2abd297629da2f587477f33ee

~~⚠️ Currently untested, awaiting access to Troll to try to replicate Network vectors in summary.~~
Alif has tested using Troll data. ✅

### CODE REVIEW

**Comment by andreas-el** [comment]
Alif Be wrote:
I think I figure out the problem. wgname is not defined for network keyword
[12:23](https://equinor.slack.com/archives/D06G22QJEKD/p1707132232260249)
we need to add network to this line https://github.com/equinor/resdata/blob/4062d1e551e087623eb123e5e58f2bcf026db387/lib/resdata/smspec_node.cpp#L567
[smspec_node.cpp](https://github.com/equinor/resdata/blob/4062d1e551e087623eb123e5e58f2bcf026db387/lib/resdata/smspec_node.cpp)
        this->var_type == RD_SMSPEC_LOCAL_WELL_VAR)
<https://github.com/[equinor/resdata](https://github.com/equinor/resdata)|equinor/resdata>equinor/resdata | Added by [GitHub](https://equinor.slack.com/services/B01UGSXJU30)
[12:24](https://equinor.slack.com/archives/D06G22QJEKD/p1707132258521859)
tested on troll dataset and seems to work

**Comment by eivindjahren** [comment]
Looks good, but are we sure that network variables always have well names? In any case, we now need to change the following: https://github.com/equinor/ert/blob/a520859ff788d42b0547cc8f523f8ecf8cecfe7d/src/ert/config/_read_summary.py#L167-L171

**Comment by alifbe** [comment]
> Looks good, but are we sure that network variables always have well names? In any case, we now need to change the following: https://github.com/equinor/ert/blob/e35e7e07b39534ac3ed83085a87a970b633dcc70/src/ert/config/_read_summary.py#L167-L170

Yes, network vector is **always** have a node name which is stored in either WGNAMES or NAMES. There are obviously some special vectors which are beginning with N but not network vector. 

See this commit https://github.com/OPM/ResInsight/pull/8990/commits/1cf2cd732fa8d8c47425a3ce76effe6b3b0bf7ea

**Comment by eivindjahren** [comment]
We checked and it seems that WGNAMES or NAMES will be present for network variables.

**Review by eivindjahren — APPROVED** [review]

**Review by eivindjahren — APPROVED** [review]
Yes, this seems to be correct.

**Pull request merged**
